// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class Tarea
{
    public int IdTarea { get; set; }

    public int IdUsuario { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public DateTime FechaVencimiento { get; set; }

    public string EstadoTarea { get; set; }

    public bool Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}